### Spring properties
# Service registers under this name
spring:
  application:
    name: ToDo-Microservice-NoteService
  cloud:
    config:
      uri: http://localhost:8888
      profile: prod 
  profiles:
    active:
    - prod
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

# HTTP Server (Tomcat) Port
server:
  port: 9100

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false